# Generated by Django 5.0.2 on 2025-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_alter_seller_markets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='markets',
            field=models.ManyToManyField(related_name='sellers', to='market_app.market'),
        ),
    ]
