# Generated by Django 5.1.6 on 2025-03-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_alter_seller_markets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='market',
            new_name='markets',
        ),
    ]
