# Generated by Django 5.1.6 on 2025-03-16 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0004_rename_market_product_markets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='markets',
            new_name='market',
        ),
    ]
