# Generated by Django 5.1.6 on 2025-03-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0005_rename_markets_product_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='markets',
            field=models.ManyToManyField(related_name='products', to='market_app.market'),
        ),
        migrations.AddField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(related_name='products', to='market_app.seller'),
        ),
    ]
